### ISSUE TITLE
enhancement: decorator-like func for controller actions

### ISSUE THREAD

**Issue by cleesmith** [josephspurrier/gowebapp#10]
Just thought it might be useful in larger web apps that allow only authenticated users for most actions and pages to have a `LoginRequired func` somewhere in the `package controller` like:

```
func LoginRequired(w http.ResponseWriter, r *http.Request) *sessions.Session {
    // kind of like a decorator for controller actions
    // similar to rails controller "before_action :authenticate_user!"
    session := session.Instance(r)
    if session.Values["id"] == nil {
        // user has not logged in, so redirect to login page:
        http.Redirect(w, r, "/login", http.StatusFound)
        return session
    }
    return session
}

func Index(w http.ResponseWriter, r *http.Request) {
    session := LoginRequired(w, r)
    v := view.New(r)
    v.Name = "home/index"
    v.Vars["name"] = session.Values["name"]
    v.Render(w)
    // the previous code which is often repeated in controller actions:
    // session := session.Instance(r)
    // if session.Values["id"] != nil {
    //  v := view.New(r)
    //  v.Name = "home/index"
    //  v.Vars["name"] = session.Values["name"]
    //  v.Render(w)
    // } else {
    //  http.Redirect(w, r, "/login", http.StatusFound)
    //  return
    // }
}
```

... this would be much DRY-er code wise.
See: [nsmsearch](https://github.com/cleesmith/nsmsearch/blob/master/controller/application.go)
Not really a proper decorator like [here](http://andyrees.github.io/2015/your-code-a-mess-maybe-its-time-to-bring-in-the-decorators/) but it works.
Thoughts?

**Comment by josephspurrier** [comment]
Current, I control permissions through middleware and routes because I feel it's easier to change those permissions in routes than having to modify code in the controller: https://github.com/josephspurrier/gowebapp/blob/master/route/route.go#L66

Is it a better practice to add that code to the controller?

**Comment by cleesmith** [comment]
I was just repeating a pattern that's common in ruby/Rails and python/Flask apps.
So there should be something like `acl.AuthenticatedOnly` in `route/middleware/acl/acl.go` ?

**Comment by josephspurrier** [comment]
Ah, gotcha. Yeah, you can use acl.DisallowAnon. It does the same thing.

https://github.com/josephspurrier/gowebapp/blob/master/route/middleware/acl/acl.go#L26

**Comment by cleesmith** [comment]
I see. This is better, even DRY-er. Thanks.
