### ISSUE TITLE
Mysql database connect Problem

### ISSUE THREAD

**Issue by yeahia2508** [josephspurrier/gowebapp#11]
error log:
database.go:83: No connection could be made because the target machine actively refused it. 2016-03-31 06:08:08 PM Running HTTP :80 
database.go:88: Database Error dial tcp 127.0.0.1:3306: connectex: No connection could be made because the target machine actively refused it.

**Comment by josephspurrier** [comment]
Could you provide more details? Are you able to connect to your MySQL database outside of the application?

**Comment by yeahia2508** [comment]
Actually I'm new in go. I'm able to connect bolt from this project but inside config.json file changing database type bolt to mysql this error is happening. Is there any additional import needed for connecting mysql? This is frist time I'm trying to connect mysql in go.

**Comment by josephspurrier** [comment]
Welcome to Go! The actual MySQL server is not actually included with the program. You need to set one up yourself. You can either download and install MySQL from their website or you can use either one of my utilities:
- Create a portable version of MySQL - https://github.com/josephspurrier/goappmation
- Run just the MySQL component of my WAMP Stack: https://github.com/josephspurrier/surfstack-wamp

**Comment by yeahia2508** [comment]
Thank you very much
