### ISSUE TITLE
Can't use go get github.com/josephspurrier/gowebapp

### ISSUE THREAD

**Issue by RahulZoldyck** [josephspurrier/gowebapp#16]
Error Saying

```
Unrecognized import path "app/route" (gowebapp.go:9:2)
Unrecognized import path "app/shared/email" (gowebapp.go:11:2)
Unrecognized import path "app/shared/recaptcha" (gowebapp.go:13:2)
Unrecognized import path "app/shared/session" (gowebapp.go:15:2)
Unrecognized import path "app/shared/view" (gowebapp.go:16:2)
Unrecognized import path "app/shared/database" (gowebapp.go:10:2)
Unrecognized import path "app/shared/jsonconfig" (gowebapp.go:12:2)
Unrecognized import path "app/shared/server" (gowebapp.go:14:2)
Unrecognized import path "app/shared/view/plugin" (gowebapp.go:17:2)
```

**Comment by RahulZoldyck** [comment]
And goDocs says the same https://godoc.org/github.com/josephspurrier/gowebapp

**Comment by josephspurrier** [comment]
Yeah, once I moved the files into the vendor directory, that problem started. I think it would be best to move the files back out of vendor and then provide a way to easily change all the import paths. Thoughts?

**Comment by josephspurrier** [comment]
Hmm, actually, `go get github.com/josephspurrier/gowebapp` works fine for me, it's just godoc that doesn't work for those libraries. Which version of Go are you using and what's your OS? I'm testing with Go 1.7-beta2 x64 on Windows 10.

**Comment by RahulZoldyck** [comment]
I use go 1.5 on ubuntu 14.04

**Comment by josephspurrier** [comment]
Did you set you environment variable? GO15VENDOREXPERIMENT=1

**Comment by josephspurrier** [comment]
Also, the latest version of this project is here: https://github.com/blue-jay/blueprint. It should fix your issue.

**Comment by josephspurrier** [comment]
I'm closing this issue. If you need any more assistance, please reopen the issue.

**Comment by AkbarMT58** [comment]
i can not using your application..when i running in cmd : " jsonconfig.go:20: open config\config.json: The system cannot find the path specified.
exit status 1"
can you explain about this ?
