### ISSUE TITLE
server.go:2161: http: multiple response.WriteHeader calls

### ISSUE THREAD

**Issue by ak2344** [josephspurrier/gowebapp#17]
Hi there, 

Really appreciate your work. I'm getting weird errors like "server.go:2161: http: multiple response.WriteHeader calls" in my error log after normal looking GET requests to the index page. It's a been a bit hard to debug and replicate.

I know this may be outside the purview of the project, but if you have any pointers on where I can look to track this down, that would be really helpful. 

Thanks!

**Comment by ak2344** [comment]
Ah never mind, I figured it out. Thanks!

**Comment by josephspurrier** [comment]
@ak2344 Would you mind sharing what was causing the issue? It may help someone else with the same problem. Also, if you have any more issues, I'd really appreciate you testing with the latest version: https://github.com/blue-jay/blueprint

**Comment by ak2344** [comment]
No problem. 

I had created my own middleware that checks the URL and forwards the user if it's invalid using     http.Redirect(...). The problem was there wasn't a "return" after that so there was further writing to the headers later on.

**Comment by josephspurrier** [comment]
Ah, I gotcha. Thanks!
