### ISSUE TITLE
How to add pagination?

### ISSUE THREAD

**Issue by k0fi** [josephspurrier/gowebapp#20]
Hi Jojeph,

Will you please explain how to add pagination to `gowebapp`?
Regarding that Pagination is almost indispensable for a real world app, that would be great if you add it to the core features. 

Thanks in advance.

**Comment by josephspurrier** [comment]
Yeah, pagination would be a good thing to add. Give me a couple days and I should be able to add it to: https://github.com/blue-jay/blueprint

**Comment by josephspurrier** [comment]
Added pagination to Blueprint: https://github.com/blue-jay/blueprint/commit/4d8caa600fa7de2b183cfcf6831418afd1b7a9f3
