### ISSUE TITLE
Is there posibility to stub database?

### ISSUE THREAD

**Issue by Amirkin** [josephspurrier/gowebapp#26]
subj

**Comment by josephspurrier** [comment]
My teams typically use a real database for unit cases because they are pretty cheap now - all it takes is a docker container with MySQL. You can see how I test database queries here: https://github.com/blue-jay/blueprint/blob/master/model/note/note_test.go

**Comment by pavelshtanko** [comment]
Lurking around github projects in search of the good app structures. 
Wondering why don't you use structs to aggregate logic inside related objects? (models, database). 
From my sight, the procedural style is not testable at all...

**Comment by josephspurrier** [comment]
Blue Jay is more testable, but I'm still not happy with it. I have another branch that has been in progress (https://github.com/blue-jay/blueprint/tree/clean-restructure), but I've been busy so I haven't finished it yet.
