### ISSUE TITLE
Error to use RenderSingle with file in child folder?

### ISSUE THREAD

**Issue by dzpt** [josephspurrier/gowebapp#28]
I want to render single file but get this error:

`Template Parse Error: open admin/test.html: no such file or directory`

```
v := view.New(r)
v.Name = "admin/test"
v.RenderSingle(w)
```

After moving test file upper one level, it works.
Why?

**Comment by josephspurrier** [comment]
Could you please provide more info on where specifically the test.html file is when it works and when it does not work?

**Comment by josephspurrier** [comment]
Closing - old issue.
