### ISSUE TITLE
How's about the backend - admin part?

### ISSUE THREAD

**Issue by dzpt** [josephspurrier/gowebapp#29]
I see you put all the routes on the same route file.
Hows about the backend and admin?.
Keeping all backend and frontend in the same binary file will causes the performance?

Since user have to load backend (route, template, shared variables, logic code ...) while using frontend?
In the runtime, all the template will be cached (allocate memory) included templates, logic code, variables,  right?

**Comment by josephspurrier** [comment]
Yes, all the routes are in the same file. You can separate them into separate files if you wish. It's just an easy way to see all the routes in one place.

It will not cause any performance issues, actually, it is highly performant. This is what's called an isomorphic web app. Currently, all the templates will be cached after the first time they are compiled.

There is no admin pages, but you can create admin pages if you wish, you just have to come up with permissions and that is logic you'll need to implement yourself.
