### ISSUE TITLE
register.go:89: Database is unavailable.

### ISSUE THREAD

**Issue by k0fi** [josephspurrier/gowebapp#30]
Hi Joseph,
I am trying to make a new gowebapp using `mariadb 10` and `go1.9.2 ` , but I get this error at registration:

```
$ go build && ./myapp 
2018-01-22 08:05:42 AM Running HTTP :8090
2018-01-22 08:05:47 AM 127.0.0.1:50590 POST /register
2018-01-22 08:05:48 AM 127.0.0.1:50590 GET /register
2018-01-22 08:05:49 AM 127.0.0.1:50590 GET /static/favicons/favicon-32x32.png
2018-01-22 08:05:57 AM 127.0.0.1:50590 POST /register
register.go:89: Database is unavailable.

```

Here is the relevant config.js:

```
	"Database": {
		"Type": "MySQL",
		"Bolt": {		
 			"Path": "gowebapp.db"
  		},
		"MongoDB": {
			"URL": "127.0.0.1",
			"Database": "myappdb"
		},
		"MySQL": {
			"Username": "myuser",
			"Password": "mypasswd",
			"Name": "myappdb",
			"Hostname": "127.0.0.1",
			"Port": 3306,
			"Parameter": "?parseTime=true"
		} 
```

I did not forget to replace the database name into `myappdb` before  importing `mysql.sql` schema to mariadb. 
In terminal, I can also connect to the database using `myuser` and `mypassword` and see 3 tables are being created on `myappdb`. 

I have also another app based on  gowebapp (created about a year a go) which is still compiles and runs fine. 
So I'm out of ideas and appreciate your hints.

**Comment by k0fi** [comment]
I realized that `UserCreate` in user.go model only expcets mongodb as database! 
That's also the case for `UserByEmail`.  
Please add the missing lines for mysql.

**Comment by josephspurrier** [comment]
Can you create a new app to test just the Go library to see if it will connect to the database?

https://mariadb.com/resources/blog/using-go-mariadb

Also, can you submit a pull request for the UserCreate and the UserByEmail?

**Comment by josephspurrier** [comment]
Closing - old issue.
