### ISSUE TITLE
vendor folder conflicting with package manager

### ISSUE THREAD

**Issue by criscola** [josephspurrier/gowebapp#31]
Hello. I see that the vendor folder is used as a folder containing all the code behind of the application... unfortunately, package managers (like dep) use this folder for storing external dependencies. This pretty much breaks everything... so it would be nice to move all the stuff in another location.

**Comment by josephspurrier** [comment]
I agree it's not a good solution. I made note of this in the readme (https://github.com/josephspurrier/gowebapp#structure). For the purposes of this project, it's sufficient even if it is not a good practice. At this point, I'm no longer maintaining this project, but followed your advice in my latest project: https://github.com/blue-jay/blueprint.
