### ISSUE TITLE
How to make a template function to add values

### ISSUE THREAD

**Issue by k0fi** [josephspurrier/gowebapp#34]
Hello Joseph,

In order to enumerate over a range of titles to start from `1` instead of `0` , I need an `add` template helper function, so that it can be used like this:

```
{{range $i , $a := .titles}}
   {{add $i 1}}. {{$a.Title}}
{{end}}
```

So I made this in add.go inside `plugin` folder:

```
package plugin

import (
	"html/template"
)

func Add() template.FuncMap {
	f := make(template.FuncMap)
	f["add"] = func(x, y int) int {
		return (x + y)
	}
	return f
}

```
But on runtime I get:

`Template Parse Error: template: frontpage.tmpl:51: function "add" not defined`

How can I fix this?

Thanks

**Comment by josephspurrier** [comment]
Make sure you add that function to config.View.SetFuncMaps():

https://github.com/josephspurrier/gowebapp/blob/master/gowebapp.go#L48
