### ISSUE TITLE
recaptcha v3 not supported

### ISSUE THREAD

**Issue by k0fi** [josephspurrier/gowebapp#39]
Hello Joeph,
The package does not work with recaptcha v.3 

I get this error.

`ERROR for site owner: Invalid key type`

recaptcha v.2 is alright though.

How can I fix this?

**Comment by josephspurrier** [comment]
Sorry for the long time between comments. I'm leveraging someone else's library for recaptcha and I'm no longer maintaining this project so I'm not sure why v3 isn't working.

https://github.com/josephspurrier/gowebapp/blob/master/vendor/app/shared/recaptcha/recaptcha.go#L7

**Comment by josephspurrier** [comment]
Closing - old issue.
