### ISSUE TITLE
How to build secretkey

### ISSUE THREAD

**Issue by glepnir** [josephspurrier/gowebapp#40]
Thank you very much for your project. I am a beginner. For the generation of secret keys, it is defined in the json file. How to generate secretkey

**Comment by k0fi** [comment]
It's just a random string. You don't need any specific tool or method to `generate` it. Just close your eyes and type some letters.

**Comment by glepnir** [comment]
> It's just a random string. You don't need any specific tool or method to `generate` it. Just close your eyes and type some letters.

tanks for your reply
