### ISSUE TITLE
How to user both MySQL and BoltDB?

### ISSUE THREAD

**Issue by k0fi** [josephspurrier/gowebapp#48]
Hello Joseph,

I'd like to use MySQL for main database and BoltDB for caching but the config allows only one db. 

I appreciate if you give instructions on how to use both?

**Comment by josephspurrier** [comment]
You can use as many as you want, you just have to remove this switch statement and use the one that you want: https://github.com/josephspurrier/gowebapp/blob/master/vendor/app/model/user.go#L61
