### ISSUE TITLE
How to add go mod to the project? 

### ISSUE THREAD

**Issue by hume12** [josephspurrier/gowebapp#50]
I'd like to add go modules to use versioning in my new project as some 3rd party packages don't work without mod anymore. 
But after runing `go mod init` ,  can no longer build  and get errrors like this:

```
go: creating new go.mod: module fancyweb
me@pc5:~/go/src/fancyweb$ go build && ./fancyweb 
vendor/app/shared/database/database.go:8:2: cannot find package "." in:
        /home/me/go/src/fancyweb/vendor/github.com/boltdb/bolt
vendor/app/controller/article-create.go:18:2: cannot find package "." in:
        /home/me/go/src/fancyweb/vendor/github.com/disintegration/imaging
vendor/app/shared/redis/pool.go:9:2: cannot find package "." in:
        /home/me/go/src/fancyweb/vendor/github.com/garyburd/redigo/redis
vendor/app/shared/database/database.go:9:2: cannot find package "." in:
        /home/me/go/src/fancyweb/vendor/github.com/go-sql-driver/mysql
vendor/app/shared/redis/util.go:8:2: cannot find package "." in:
        /home/me/go/src/fancyweb/vendor/github.com/gomodule/redigo/redis 
vendor/app/shared/session/session.go:6:2: cannot find package "." in:
        /home/me/go/src/fancyweb/vendor/github.com/gorilla/sessions
vendor/app/shared/recaptcha/recaptcha.go:7:2: cannot find package "." in:
        /home/me/go/src/fancyweb/vendor/github.com/haisum/recaptcha
vendor/app/shared/database/database.go:10:2: cannot find package "." in:
        /home/me/go/src/fancyweb/vendor/github.com/jmoiron/sqlx
```

How can I fix it?

**Comment by hume12** [comment]
This might not be the ideal solution, but I resolved the problem by moving `app` to the root, getting rid of `vendor` folder and adding my app's name to the `app/` imports:

```
#cd /path/to/fancyweb  
#cp -r vendor/* .
#rm -rf vendor
```

and then I replaced all `app/*` imports to `fancyweb/app/*` (it's easy in vscode, just press `Ctrl+H` for batch replace)
After that I could 

```
#go mod init
#go mod tidy
```
That's it. Welcome to go modules.

**Comment by josephspurrier** [comment]
Please use this branch for modules: https://github.com/josephspurrier/gowebapp/tree/modules

**Comment by hume12** [comment]
Using imports  like `"github.com/josephspurrier/gowebapp/app/model"` what happens if  I want to make some changes to  the `model` myself?
TBH I don't like this sort of dependence on github imports. Isn't there a better solution?

**Comment by josephspurrier** [comment]
Go recommends using the `replace` directive for modules: https://stackoverflow.com/a/56792766

**Comment by josephspurrier** [comment]
Otherwise, you can just do a find and replace on the whole project and change it to your own path.
