### ISSUE TITLE
two submit forms in one page

### ISSUE THREAD

**Issue by vjey23** [josephspurrier/gowebapp#7]
Hello,
 I am trying to use two submit forms on one page. It is working fine for one form but for second form I am getting this msg "Your token has expired". Can you help me get this resolve?

**Comment by josephspurrier** [comment]
Yep. Thanks for bringing this up. I updated the code and added an explanation to the readme of the package that is responsible for the message: https://github.com/josephspurrier/csrfbanana#multiple-forms-on-the-same-page
